import React from "react";
import Tariff from "../Tariff/Tariff";

export default function TariffList() {
  const tariffs = [
    {
      id: 1,
      title: "Мой онлайн+",
      price: 500,
      withOutLimit: "+безлимит на Tele2 в России",
      text: "На остальные номера в В России",
      time: 500,
      sms: 50,
      socialMediaInclude: true,
      unlimOnRus: false,
      rowming: false,
      traffic: 40,
      itsHit: true,
      unlimInternet: false,
      withOutAmount: false,
      classic: false,
      forDevices: false,
      forDay: false
    },
    {
      id: 2,
      title: "Везде онлайн",
      price: 400,
      withOutLimit: "+безлимит на Tele2 в России",
      text: "На остальные номера в В России",
      time: 500,
      sms: 0,
      unlimOnRus: false,
      rowming: false,
      socialMediaInclude: true,
      traffic: 15,
      itsHit: false,
      unlimInternet: false,
      withOutAmount: false,
      classic: false,
      forDevices: false,
      forDay: false
    },
    {
      id: 3,
      title: "Мой онлайн",
      price: 700,
      withOutLimit: "+безлимит на Tele2 в России",
      text: "На остальные номера в В России",
      time: 800,
      sms: 0,
      rowming: true,
      unlimOnRus: false,
      socialMediaInclude: true,
      traffic: 30,
      itsHit: false,
      unlimInternet: false,
      withOutAmount: false,
      classic: false,
      forDevices: false,
      forDay: false
    },
    {
      id: 4,
      title: "Мой разговор",
      price: 200,
      withOutLimit: "+безлимит на Tele2 в России",
      text: "На остальные номера в В России",
      time: 200,
      sms: 0,
      rowming: false,
      unlimOnRus: false,
      socialMediaInclude: false,
      traffic: 2,
      itsHit: false,
      unlimInternet: false,
      withOutAmount: false,
      classic: false,
      forDevices: false,
      forDay: false
    },
    {
      id: 5,
      title: "Мой Tele2",
      price: 7,
      withOutLimit: "+безлимит на Tele2 в России",
      text: "На остальные номера в В России",
      time: 0,
      sms: 0,
      unlimOnRus: false,
      rowming: false,
      socialMediaInclude: false,
      traffic: 5,
      itsHit: false,
      unlimInternet: false,
      withOutAmount: false,
      classic: false,
      forDevices: false,
      forDay: true
    },
    {
      id: 6,
      title: "Безлимит",
      price: 650,
      withOutLimit: "+безлимит на Tele2 в России",
      text: "На остальные номера в В России",
      time: 500,
      sms: 50,
      unlimOnRus: false,
      rowming: false,
      socialMediaInclude: false,
      traffic: 0,
      itsHit: false,
      unlimInternet: true,
      withOutAmount: false,
      classic: false,
      forDevices: false,
      forDay: false
    },
    {
      id: 7,
      title: "Премиум",
      price: 1500,
      withOutLimit: "",
      text: "На остальные номера в В России",
      time: 2000,
      sms: 500,
      unlimOnRus: false,
      rowming: false,
      socialMediaInclude: false,
      traffic: 50,
      itsHit: false,
      unlimInternet: false,
      withOutAmount: false,
      classic: false,
      forDevices: false,
      forDay: false
    },
    {
      id: 8,
      title: "Мой онлайн",
      price: 0,
      withOutLimit: "",
      text: "На остальные номера в В России",
      time: 0,
      sms: 0,
      socialMediaInclude: false,
      rowming: false,
      unlimOnRus: false,
      traffic: 0,
      itsHit: false,
      unlimInternet: false,
      withOutAmount: true,
      classic: true,
      forDevices: false,
      forDay: false
    },
    {
      id: 9,
      title: "Классический",
      price: 0,
      withOutLimit: "",
      text: "На остальные номера в В России",
      time: 0,
      sms: 0,
      unlimOnRus: false,
      socialMediaInclude: false,
      rowming: false,
      traffic: 0,
      itsHit: false,
      unlimInternet: false,
      withOutAmount: true,
      classic: false,
      forDevices: true,
      forDay: false
    },
    {
      id: 10,
      title: "Интернет для вещей",
      price: 100,
      withOutLimit: "",
      text: "На остальные номера в В России",
      time: 30,
      sms: 100,
      unlimOnRus: false,
      socialMediaInclude: false,
      rowming: false,
      traffic: 0.3,
      itsHit: false,
      unlimInternet: false,
      withOutAmount: false,
      classic: false,
      forDevices: false,
      forDay: false
    }
  ];
  return (
    <>
      {tariffs.map(o => (
        <Tariff tariff={o} />
      ))}
    </>
  );
}
